Add-linters
Jeanbulambo/Hello-World3 pull request #1
Opened 2022-05-26 15:34 UTC by Jeanbulambo

using linters in this project

2022-05-26 16:04 UTC, Kandy-Peter requested changes
Hi @tresorsawasawa 

Good job so far! I know you have worked hard on making this milestone. There is an issue that you still need to work on to go to the next project but you are almost there!

![almost-there-almost](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] As required, your PR should a meaningful description of what you did in this part of the project. Please, add some more descriptions for the correct Usage of Github flow.
```
In this pull request, I implemented the following elements:

- Create an `index.html` file
- Add Linters
- etc

```

- [x] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 16:04 UTC, Kandy-Peter commented on README.md
> +
- [ ] As requested, In this project, you should use the[README template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse.

2022-05-26 21:30 UTC, Jeanbulambo commented
Please, for required changes, i don't understand very well. what should I do exactly.  Am I going to do again the project from the beginning then push so I may add description or I can do it from github?

2022-05-26 21:36 UTC, Kandy-Peter commented
You can do it from GitHub, just click on the right top dots then edit and save.

2022-05-26 22:03 UTC, Jeanbulambo commented
Please see a screenshot of what I edited according to the requirement and your orientation
![pull](https://user-images.githubusercontent.com/103334079/170587223-fbb2832f-b1fe-4bc0-96fd-8d9305509886.png).

Should I submit it like this?

2022-05-27 09:38 UTC, Jeanbulambo reviewed
comment pull request I did and update README file using Microverse Template

2022-05-27 20:58 UTC, omarsalem7 requested changes
Hi @Jeanbulambo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive PR

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Nothing to mention.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 20:58 UTC, omarsalem7 commented on README.md
> +> Description the project.
- [ ] You are make great work, but you should update the readme template according to your project. Please, add the project name `Hello world` for example.
- [ ] Also add a description of the project for example `This is my first project hello world in Microverse`

2022-05-27 20:58 UTC, omarsalem7 commented on README.md
> +### Deployment
- [ ] Kindly remove this and add the instructions for how to clone your repository

2022-05-28 03:05 UTC, muneebulrehman approved these changes
Hi @Jeanbulambo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Project Approved.

## Highlights
- Good follow up with previous reviewers
- All linter checks passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 03:05 UTC, muneebulrehman commented on README.md
> +### Press Enter to create your local clone.
Optional.
Only use headings for a section heading. The rest of the content can be simple text or a list as you may desire.

2022-05-28 03:05 UTC, muneebulrehman commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Optional.
On any project, on which you are working alone, You can remove Authors heading and simply use **Author** as a heading followed with your social handles.

2022-05-28 16:29 UTC, merged